CPSEC-395: Docker example for KSQL OAuth
confluentinc/cp-all-in-one pull request #163
Opened 2024-10-16 06:52 UTC by prabhashkr

### Description 
https://confluentinc.atlassian.net/browse/CPSEC-395
Adds support for KSQL OAuth

### Author Validation
Validated cp-all-in-one-security

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

2024-10-16 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/confluentinc/cp-all-in-one?pullRequest=163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/confluentinc/cp-all-in-one?pullRequest=163) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/confluentinc/cp-all-in-one?pullRequest=163) it.</sub>

2024-10-17 07:03 UTC, nsharma-git reviewed
Thanks. 
Overall looks good. Left a few minor comments.

2024-10-17 09:37 UTC, prabhashkr commented
@nsharma-git I haven't included KSQL CLI in this docker example as we don't have SSO on it yet. It still uses basic credentials.
Should I include it?

2024-10-17 10:04 UTC, nsharma-git approved these changes
Thanks!

2024-11-01 15:17 UTC, davetroiano requested changes
Thank you @prabhashkr overall this was smooth and easy to follow

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
>  127.0.0.1       broker
Add a prereqs section right under `Getting started`:

```

### Prerequisites

* [`jq`](https://github.com/jqlang/jq/wiki/Installation), which is used to process JSON responses throughout this example
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +5. Configure Schema Registry, Connect, KSQL and Control Center to authenticate via OAuth.
```suggestion
5. Configure Schema Registry, Connect, ksqlDB and Control Center to authenticate via OAuth.
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +7. Configure Control Center to talk to MDS, Schema Registry, KSQL and Connect.
```suggestion
7. Configure Control Center to talk to MDS, Schema Registry, ksqlDB and Connect.
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +### KSQL RBAC using OAuth
```suggestion
### ksqlDB RBAC using OAuth
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +#### Ensure token is valid and the KSQL service is running fine
```suggestion
#### Ensure token is valid and the ksqlDB service is running fine
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +curl --http1.1 \                                                                                                      ✘ INT 00:16:18
```suggestion
curl --http1.1 \
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +curl --http1.1 \                                                                                                      ✘ INT 00:16:18
for the 4 curl commands to ksqlDB REST API, suggest tacking on `| jq` so that the output is prettier. And then the 4 "Output should resemble" snippets probably don't need the full JSON output in the README. e.g. something shorter like "The JSON output should include the `ABC` stream" (for query 1 below) would suffice

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/README.md
> +#### Execute KSQL commands
```suggestion
#### Execute ksqlDB commands
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/docker-compose.yml
> +      # KSQL
```suggestion
      # ksqlDB
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/docker-compose.yml
> +      # Enable RBAC on KSQL server
```suggestion
      # Enable RBAC on ksqlDB server
```

2024-11-01 15:17 UTC, davetroiano commented on cp-all-in-one-security/oauth/docker-compose.yml
> +      # KSQL to SR on OAuth
```suggestion
      # ksqlDB to SR on OAuth
```

2024-11-05 14:31 UTC, davetroiano approved these changes
lgtm!

2024-11-05 14:32 UTC, merged